# Generated by Django 5.1.4 on 2025-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfzeroum',
            name='simbolo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
