# Generated by Django 5.1.4 on 2025-01-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0002_rfzeroum_simbolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('idOrigem', models.CharField(max_length=20)),
                ('dataInstalacaoSensor', models.DateField()),
                ('descricaoInstalacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroFabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idOrigem', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('idOrigem', models.CharField(max_length=20)),
                ('dataInstalacao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('IdFabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrofabricante')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroTipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('idOrigem', models.CharField(max_length=20)),
                ('leituraMinimaOperacao', models.FloatField()),
                ('leituraMaximaOperacao', models.FloatField()),
                ('leituraMinimaDesligado', models.FloatField()),
                ('leituraMaximaDesligado', models.FloatField()),
                ('leituraMinimaAlerta', models.FloatField()),
                ('leituraMaximaAlerta', models.FloatField()),
                ('leituraMinimaInterromper', models.FloatField()),
                ('leituraMaximaInterromper', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroUnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('idOrigem', models.CharField(max_length=20)),
                ('simbolo', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RfZeroUm',
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='idFabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrofabricante'),
        ),
        migrations.AddField(
            model_name='cadastroequipamento',
            name='idSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrosensor'),
        ),
        migrations.AddField(
            model_name='cadastrosensor',
            name='IdTipoSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrotiposensor'),
        ),
        migrations.AddField(
            model_name='cadastrotiposensor',
            name='IdUnidadeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrounidademedida'),
        ),
    ]
