# Generated by Django 5.1.4 on 2025-01-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0003_cadastroequipamento_cadastrofabricante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroequipamento',
            name='dataInstalacaoSensor',
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='idSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='rfs.cadastrosensor'),
        ),
    ]
