# Generated by Django 5.1.4 on 2025-01-13 02:26

import django.db.models.deletion
import rfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0004_remove_cadastroequipamento_datainstalacaosensor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroequipamento',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='cadastrofabricante',
            options={'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='cadastrosensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterModelOptions(
            name='cadastrotiposensor',
            options={'verbose_name': 'Tipo de Sensor', 'verbose_name_plural': 'Tipos de Sensores'},
        ),
        migrations.AlterModelOptions(
            name='cadastrounidademedida',
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medidas'},
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='descricaoInstalacao',
            field=models.TextField(verbose_name='Descrição de Instalação'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='idFabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrofabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='idOrigem',
            field=models.CharField(max_length=20, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='idSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrosensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='idOrigem',
            field=models.CharField(max_length=20, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='telefone',
            field=models.CharField(max_length=11, validators=[rfs.models.validar_telefone], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='IdFabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrofabricante', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='IdTipoSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrotiposensor', verbose_name='Tipo de Sensor'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='dataInstalacao',
            field=models.DateField(verbose_name='Data de Instalação'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='idOrigem',
            field=models.CharField(max_length=20, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='IdUnidadeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrounidademedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='idOrigem',
            field=models.CharField(max_length=20, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMaximaAlerta',
            field=models.FloatField(verbose_name='Leitura Máxima de Alerta'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMaximaDesligado',
            field=models.FloatField(verbose_name='Leitura Máxima Desligado'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMaximaInterromper',
            field=models.FloatField(verbose_name='Leitura Máxima Interromper'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMaximaOperacao',
            field=models.FloatField(verbose_name='Leitura Máxima de Operação'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMinimaAlerta',
            field=models.FloatField(verbose_name='Leitura Mínima de Alerta'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMinimaDesligado',
            field=models.FloatField(verbose_name='Leitura Mínima Desligado'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMinimaInterromper',
            field=models.FloatField(verbose_name='Leitura Mínima Interromper'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='leituraMinimaOperacao',
            field=models.FloatField(verbose_name='Leitura Mínima de Operação'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='idOrigem',
            field=models.CharField(max_length=20, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='simbolo',
            field=models.CharField(max_length=20, verbose_name='Símbolo'),
        ),
    ]
