# Generated by Django 5.1.4 on 2025-01-17 16:21

import django.db.models.deletion
import rfs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0005_alter_cadastroequipamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroequipamento',
            name='idSensor',
        ),
        migrations.RemoveField(
            model_name='cadastrosensor',
            name='dataInstalacao',
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='idOrigem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, validators=[rfs.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='idOrigem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrofabricante',
            name='telefone',
            field=models.CharField(max_length=15, validators=[rfs.validators.validar_telefone], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='idOrigem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='idOrigem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id de Origem'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='idOrigem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id de Origem'),
        ),
        migrations.CreateModel(
            name='InstalacaoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInstalacaoSensor', models.DateField(verbose_name='Data de instalação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('idEquipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastroequipamento', verbose_name='Id do Equipamento')),
                ('idSensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfs.cadastrosensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Instalação de Sensor',
                'verbose_name_plural': 'Instalação de Sensores',
            },
        ),
    ]
