# Generated by Django 5.1.4 on 2025-01-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0006_remove_cadastroequipamento_idsensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacaosensor',
            name='data_remocao_sensor',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Remoção'),
        ),
        migrations.AlterField(
            model_name='cadastroequipamento',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrosensor',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrotiposensor',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrounidademedida',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
